export const siteConfig = {
  name: "PYU Admissions Admin",
  shortName: "PYU",
  description: "Hệ thống quản trị dữ liệu tuyển sinh Phu Yen University.",
  navigation: [
    {
      id: "institution-info",
      label: "Thông tin trường",
      subtitle: "Institution Info",
      path: "/institution-info",
      icon: "institution",
    },
    {
      id: "programs-majors",
      label: "Ngành đào tạo",
      subtitle: "Programs / Majors",
      path: "/programs-majors",
      icon: "programs",
    },
    {
      id: "admissions",
      label: "Tuyển sinh",
      subtitle: "Admissions / Enrollment",
      path: "/admissions",
      icon: "admissions",
      children: [
        { id: "admissions-general", label: "Thông tin chung (General)", path: "/admissions/general" },
        { id: "admissions-cutoff", label: "Điểm chuẩn (Cutoff)", path: "/admissions/cutoff" },
        { id: "admissions-admitted", label: "Trúng tuyển (Admitted)", path: "/admissions/admitted" },
        { id: "admissions-additional", label: "Hướng dẫn & Quy đổi (Additional)", path: "/admissions/additional" },
      ],
    },
    {
      id: "tuition-financial-aid",
      label: "Học phí & học bổng",
      subtitle: "Tuition & Financial Aid",
      path: "/tuition-financial-aid",
      icon: "tuition",
    },
    {
      id: "campus-facilities",
      label: "Cơ sở vật chất",
      subtitle: "Campus / Facilities",
      path: "/campus-facilities",
      icon: "campus",
    },
    {
      id: "student-life",
      label: "Cuộc sống sinh viên",
      subtitle: "Student Life",
      path: "/student-life",
      icon: "student-life",
    },
    {
      id: "application-requirements",
      label: "Hồ sơ & thủ tục",
      subtitle: "Application Requirements",
      path: "/application-requirements",
      icon: "application",
    },
    {
      id: "schedule-deadlines",
      label: "Lịch & deadline",
      subtitle: "Schedule & Deadlines",
      path: "/schedule-deadlines",
      icon: "schedule",
    },
    {
      id: "housing-dormitory",
      label: "Ký túc xá",
      subtitle: "Housing / Dormitory",
      path: "/housing-dormitory",
      icon: "housing",
    },
    {
      id: "contact-support",
      label: "Liên hệ & hỗ trợ",
      subtitle: "Contact & Support",
      path: "/contact-support",
      icon: "contact",
    },
  ],
};
